# site settings

title: Nayana Dasgupta
description: Nayana Dasgupta's Personal Website
taglong: Software Engineer
tagshort: Software Engineer
url: https://nayanadasgupta.com
baseurl: ""
permalink: pretty
repo: https://github.com/nayanadasgupta/nayanadasgupta.github.io

# author settings

author:
    name: Nayana Dasgupta
    # email: username@domain.com
# photo: /assets/jpg/filename.jpg

social:
    github: nayanadasgupta
    linkedin: nayanadasgupta

# build settings

exclude:
    - LICENSE
    - README.md

plugins:
    - jekyll-feed
    - jekyll-gist
    - jekyll-paginate-v2
    - jekyll-seo-tag
    - jekyll-sitemap

whitelist:
    - jekyll-sitemap

sass:
    sass_dir: _sass
    style: compressed
    sourcemap: never

feed:
    path: atom.xml

autopages:
    enabled: false

pagination:
    enabled: true
    per_page: 1
    sort_reverse: true
    permalink: /:num/
    title: ":title &middot; Page :num"
